In [373]:
import pandas as pd

# 1. 0. Alibaba

In [384]:
prediction_2600_alibaba = pd.read_csv("Export/alibaba/alibaba_prediction_variantB_2600_clusterwise.csv").drop(columns = ['Unnamed: 0'])
prediction_5000_alibaba = pd.read_csv("Export/alibaba/alibaba_prediction_variantB_5000_clusterwise.csv").drop(columns = ['Unnamed: 0'])
prediction_10000_alibaba = pd.read_csv("Export/alibaba/alibaba_prediction_variantB_10000_clusterwise.csv").drop(columns = ['Unnamed: 0'])

In [385]:
all_predictions_alibaba = pd.DataFrame()

## 1.1 Preprocessing

In [386]:
prediction_2600_alibaba['users_after_classifier']=2600
prediction_2600_alibaba['cluster_prediction']= prediction_2600_alibaba.cluster_id.apply(lambda x:x[:x.rindex('_')])
prediction_5000_alibaba['users_after_classifier']=5000
prediction_5000_alibaba['cluster_prediction']= prediction_5000_alibaba.cluster_id.apply(lambda x:x[:x.rindex('_')])
prediction_10000_alibaba['users_after_classifier']=10000
prediction_10000_alibaba['cluster_prediction']= prediction_10000_alibaba.cluster_id.apply(lambda x:x[:x.rindex('_')])
prediction_10000_alibaba.sample(3)

,uid,cluster_id,step,method,model,RMSE,date,predicted_value,true_value,users_after_classifier,cluster_prediction
2503072,88687,GMM_Pair_9.0,after_classifier,clustered_clusterwise,trmf,0.011786,2018-10-10 16:00:00,-0.000054,0.0,10000,GMM_Pair
1700942,18873,GMM_Voting_1.0,after_classifier,clustered_clusterwise,trmf,0.087745,2018-10-01 16:00:00,0.000000,0.0,10000,GMM_Voting
3588382,42272,supercluster_0.0,after_classifier,clustered,theta,1.513159,2018-11-21 16:00:00,0.330411,0.0,10000,supercluster

In [387]:
all_predictions_alibaba = all_predictions_alibaba.append(prediction_2600_alibaba)
all_predictions_alibaba = all_predictions_alibaba.append(prediction_5000_alibaba)
all_predictions_alibaba = all_predictions_alibaba.append(prediction_10000_alibaba)

In [388]:
all_predictions_alibaba.pivot_table(index=['model','step','method'], columns=['users_after_classifier','cluster_prediction'], values='RMSE').round(3)

users_after_classifier                           2600              \
cluster_prediction                            GMM_Pair GMM_Voting
model step              method
theta after_classifier  clustered                0.930      1.247
      before_classifier clustered                0.830      1.274
trmf  after_classifier  clustered_clusterwise    0.432      1.204
      before_classifier clustered_clusterwise    0.772      1.230

users_after_classifier                                        5000   \
cluster_prediction                            supercluster GMM_Pair
model step              method
theta after_classifier  clustered                    1.279    1.120
      before_classifier clustered                    1.314    0.830
trmf  after_classifier  clustered_clusterwise        0.634    1.082
      before_classifier clustered_clusterwise        1.270    0.772

users_after_classifier                                                 \
cluster_prediction                            GMM_Voting supercluster
model step              method
theta after_classifier  clustered                  1.280        1.291
      before_classifier clustered                  1.274        1.314
trmf  after_classifier  clustered_clusterwise      0.227        0.520
      before_classifier clustered_clusterwise      1.230        1.270

users_after_classifier                           10000
cluster_prediction                            GMM_Pair GMM_Voting supercluster
model step              method
theta after_classifier  clustered                1.406      1.460        1.472
      before_classifier clustered                0.830      1.274        1.314
trmf  after_classifier  clustered_clusterwise    0.367      0.250        1.437
      before_classifier clustered_clusterwise    0.772      1.230        1.270

## 1.2 Adding predictions without clusterwise

In [389]:
users = 2600
all_predictions_alibaba_wo_clusterwise_2600 =   pd.read_csv("Export/alibaba/alibaba_prediction_both_methods_"+str(users)+"_.csv").drop(columns = ['Unnamed: 0'])
all_predictions_alibaba_wo_clusterwise_2600['users_after_classifier']=users
all_predictions_alibaba_wo_clusterwise_2600['cluster_prediction']= all_predictions_alibaba_wo_clusterwise_2600.cluster_id.apply(lambda x:x if (x=='none') else ('cluster_'+ x[-1:]))

In [390]:
all_predictions_alibaba_wo_clusterwise_2600.pivot_table(index=['model','step','method'], columns=['users_after_classifier','cluster_prediction'], values='RMSE').round(3)

users_after_classifier    2600
cluster_prediction        none
model step     method
theta all_data all_data  1.296
trmf  all_data all_data  1.370

In [392]:
users = 5000
all_predictions_alibaba_wo_clusterwise_5000 =   pd.read_csv("Export/alibaba/alibaba_prediction_both_methods_"+str(users)+"_.csv").drop(columns = ['Unnamed: 0'])
all_predictions_alibaba_wo_clusterwise_5000['users_after_classifier']=users
all_predictions_alibaba_wo_clusterwise_5000['cluster_prediction']= all_predictions_alibaba_wo_clusterwise_5000.cluster_id.apply(lambda x:x if (x=='none') else ('cluster_'+ x[-1:]))
users = 10000
all_predictions_alibaba_wo_clusterwise_10000 =   pd.read_csv("Export/alibaba/alibaba_prediction_both_methods_"+str(users)+"_.csv").drop(columns = ['Unnamed: 0'])
all_predictions_alibaba_wo_clusterwise_10000['users_after_classifier']=users
all_predictions_alibaba_wo_clusterwise_10000['cluster_prediction']= all_predictions_alibaba_wo_clusterwise_10000.cluster_id.apply(lambda x:x if (x=='none') else ('cluster_'+ x[-1:]))

In [393]:
all_predictions_alibaba = all_predictions_alibaba.append(all_predictions_alibaba_wo_clusterwise_2600)
all_predictions_alibaba = all_predictions_alibaba.append(all_predictions_alibaba_wo_clusterwise_5000)
all_predictions_alibaba = all_predictions_alibaba.append(all_predictions_alibaba_wo_clusterwise_10000)

In [401]:
all_predictions_alibaba.pivot_table(index=['model','step','method'], columns=['users_after_classifier','cluster_prediction'], values='RMSE').round(3)

users_after_classifier                           2600                     \
cluster_prediction                            GMM_Pair GMM_Voting   none
model step              method
theta after_classifier  clustered                0.930      1.247    NaN
      all_data          all_data                   NaN        NaN  1.296
      before_classifier clustered                0.830      1.274    NaN
trmf  after_classifier  clustered_clusterwise    0.432      1.204    NaN
      all_data          all_data                   NaN        NaN  1.370
      before_classifier clustered_clusterwise    0.772      1.230    NaN

users_after_classifier                                        5000   \
cluster_prediction                            supercluster GMM_Pair
model step              method
theta after_classifier  clustered                    1.279    1.120
      all_data          all_data                       NaN      NaN
      before_classifier clustered                    1.314    0.830
trmf  after_classifier  clustered_clusterwise        0.634    1.082
      all_data          all_data                       NaN      NaN
      before_classifier clustered_clusterwise        1.270    0.772

users_after_classifier                                                        \
cluster_prediction                            GMM_Voting   none supercluster
model step              method
theta after_classifier  clustered                  1.280    NaN        1.291
      all_data          all_data                     NaN  2.448          NaN
      before_classifier clustered                  1.274    NaN        1.314
trmf  after_classifier  clustered_clusterwise      0.227    NaN        0.520
      all_data          all_data                     NaN  1.490          NaN
      before_classifier clustered_clusterwise      1.230    NaN        1.270

users_after_classifier                           10000                    \
cluster_prediction                            GMM_Pair GMM_Voting   none
model step              method
theta after_classifier  clustered                1.406      1.460    NaN
      all_data          all_data                   NaN        NaN  1.602
      before_classifier clustered                0.830      1.274    NaN
trmf  after_classifier  clustered_clusterwise    0.367      0.250    NaN
      all_data          all_data                   NaN        NaN  1.798
      before_classifier clustered_clusterwise    0.772      1.230    NaN

users_after_classifier
cluster_prediction                            supercluster
model step              method
theta after_classifier  clustered                    1.472
      all_data          all_data                       NaN
      before_classifier clustered                    1.314
trmf  after_classifier  clustered_clusterwise        1.437
      all_data          all_data                       NaN
      before_classifier clustered_clusterwise        1.270

# 2.0 CDNOW

In [356]:
prediction_2600_cdnow = pd.read_csv("Export/cdnow/cdnow_prediction_variantB_2600_clusterwise.csv").drop(columns = ['Unnamed: 0'])
prediction_5000_cdnow = pd.read_csv("Export/cdnow/cdnow_prediction_variantB_5000_clusterwise.csv").drop(columns = ['Unnamed: 0'])
prediction_10000_cdnow = pd.read_csv("Export/cdnow/cdnow_prediction_variantB_10000_clusterwise.csv").drop(columns = ['Unnamed: 0'])

In [357]:
all_predictions_cdnow = pd.DataFrame()

## 2.1 Preprocessing

In [358]:
prediction_2600_cdnow['users_after_classifier']=2600
prediction_2600_cdnow['cluster_prediction']= prediction_2600_cdnow.cluster_id.apply(lambda x:x[:x.rindex('_')])
prediction_5000_cdnow['users_after_classifier']=5000
prediction_5000_cdnow['cluster_prediction']= prediction_5000_cdnow.cluster_id.apply(lambda x:x[:x.rindex('_')])
prediction_10000_cdnow['users_after_classifier']=10000
prediction_10000_cdnow['cluster_prediction']= prediction_10000_cdnow.cluster_id.apply(lambda x:x[:x.rindex('_')])
prediction_10000_cdnow.sample(2)

,id,cluster_id,step,method,model,RMSE,date,predicted_value,true_value,users_after_classifier,cluster_prediction
447613,23214,GMM_Pair_6.0,before_classifier,clustered,theta,0.558531,1998-06-23,-0.001643,0.0,2600,GMM_Pair
1053164,20501,GMM_Voting_5.0,after_classifier,clustered,theta,4.284638,1998-05-31,0.006996,0.0,2600,GMM_Voting

In [361]:
all_predictions_cdnow = all_predictions_cdnow.append(prediction_2600_cdnow)
all_predictions_cdnow = all_predictions_cdnow.append(prediction_5000_cdnow)
all_predictions_cdnow = all_predictions_cdnow.append(prediction_10000_cdnow)

In [362]:
all_predictions_cdnow.pivot_table(index=['model','step','method'], columns=['users_after_classifier','cluster_prediction'], values='RMSE').round(3)

users_after_classifier                           2600                5000   \
cluster_prediction                            GMM_Pair GMM_Voting GMM_Pair
model step              method
theta after_classifier  clustered                2.025      2.108    2.411
      before_classifier clustered                1.922      2.018    1.922
trmf  after_classifier  clustered_clusterwise    1.550      2.114    2.402
      before_classifier clustered_clusterwise    1.674      2.020    1.674

users_after_classifier                                      10000
cluster_prediction                            GMM_Voting GMM_Pair GMM_Voting
model step              method
theta after_classifier  clustered                  2.594    2.266      2.355
      before_classifier clustered                  2.018    1.922      2.018
trmf  after_classifier  clustered_clusterwise      1.324    2.265      1.281
      before_classifier clustered_clusterwise      2.020    1.674      2.020

## 2.2 Adding predictions without clusterwise

In [363]:
users = 2600
all_predictions_cdnow_wo_clusterwise_2600 =   pd.read_csv("Export/cdnow/cdnow_prediction_both_methods_"+str(users)+"_.csv").drop(columns = ['Unnamed: 0'])
all_predictions_cdnow_wo_clusterwise_2600['users_after_classifier']=users
all_predictions_cdnow_wo_clusterwise_2600['cluster_prediction']= all_predictions_cdnow_wo_clusterwise_2600.cluster_id.apply(lambda x:x if (x=='none') else ('cluster_'+ x[-1:]))

In [364]:
all_predictions_cdnow_wo_clusterwise_2600.pivot_table(index=['model','step','method'], columns=['users_after_classifier','cluster_prediction'], values='RMSE').round(3)

users_after_classifier    2600
cluster_prediction        none
model step     method
theta all_data all_data  2.780
trmf  all_data all_data  2.723

In [365]:
users = 5000
all_predictions_cdnow_wo_clusterwise_5000 =   pd.read_csv("Export/cdnow/cdnow_prediction_both_methods_"+str(users)+"_.csv").drop(columns = ['Unnamed: 0'])
all_predictions_cdnow_wo_clusterwise_5000['users_after_classifier']=users
all_predictions_cdnow_wo_clusterwise_5000['cluster_prediction']= all_predictions_cdnow_wo_clusterwise_5000.cluster_id.apply(lambda x:x if (x=='none') else ('cluster_'+ x[-1:]))
users = 10000
all_predictions_cdnow_wo_clusterwise_10000 =   pd.read_csv("Export/cdnow/cdnow_prediction_both_methods_"+str(users)+"_.csv").drop(columns = ['Unnamed: 0'])
all_predictions_cdnow_wo_clusterwise_10000['users_after_classifier']=users
all_predictions_cdnow_wo_clusterwise_10000['cluster_prediction']= all_predictions_cdnow_wo_clusterwise_10000.cluster_id.apply(lambda x:x if (x=='none') else ('cluster_'+ x[-1:]))

In [367]:
all_predictions_cdnow = all_predictions_cdnow.append(all_predictions_cdnow_wo_clusterwise_2600)
all_predictions_cdnow = all_predictions_cdnow.append(all_predictions_cdnow_wo_clusterwise_5000)
all_predictions_cdnow = all_predictions_cdnow.append(all_predictions_cdnow_wo_clusterwise_10000)

In [368]:
all_predictions_cdnow.pivot_table(index=['model','step','method'], columns=['users_after_classifier','cluster_prediction'], values='RMSE').round(3)

users_after_classifier                           2600                     \
cluster_prediction                            GMM_Pair GMM_Voting   none
model step              method
theta after_classifier  clustered                2.025      2.108    NaN
      all_data          all_data                   NaN        NaN  2.780
      before_classifier clustered                1.922      2.018    NaN
trmf  after_classifier  clustered_clusterwise    1.550      2.114    NaN
      all_data          all_data                   NaN        NaN  2.723
      before_classifier clustered_clusterwise    1.674      2.020    NaN

users_after_classifier                           5000                     \
cluster_prediction                            GMM_Pair GMM_Voting   none
model step              method
theta after_classifier  clustered                2.411      2.594    NaN
      all_data          all_data                   NaN        NaN  2.638
      before_classifier clustered                1.922      2.018    NaN
trmf  after_classifier  clustered_clusterwise    2.402      1.324    NaN
      all_data          all_data                   NaN        NaN  2.596
      before_classifier clustered_clusterwise    1.674      2.020    NaN

users_after_classifier                           10000
cluster_prediction                            GMM_Pair GMM_Voting   none
model step              method
theta after_classifier  clustered                2.266      2.355    NaN
      all_data          all_data                   NaN        NaN  2.782
      before_classifier clustered                1.922      2.018    NaN
trmf  after_classifier  clustered_clusterwise    2.265      1.281    NaN
      all_data          all_data                   NaN        NaN  3.143
      before_classifier clustered_clusterwise    1.674      2.020    NaN